name: Deploy to Firebase Hosting on merge


on:
  push:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: 'new-app-group'

    steps:
      # checks out the repo
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
            cache: true
            cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'

      - name: Run flutter analyze
        run: flutter analyze

      - name: Flutter test
        run: flutter test

      - name: Build web app
        run: flutter build web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEW_MH_APP_1 }}'
          channelId: live
          projectId: new-mh-app-1

      
