name: Deploy to Firebase Hosting on merge


on:
  push:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: 'new-app-group'

    steps:
      # checks out the repo
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
            cache: true
            cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'

      - name: Run flutter analyze
        run: flutter analyze

      - name: Flutter test
        run: flutter test
